sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kiran/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kiran/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-689502831008"
  bucket: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
